### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by kreativmonkey** [degregat/ppdt#1]
Hi,

wir haben auf Devpost zwar schon einen Kommentar hinterlassen aber das Benachrichtigungssystem dort ist nicht ganz so gut wie bei Github. Schau dir mal unser Projekt an [BanDemic](https://devpost.com/software/008_a_corona_tracking_infectionchain) die Überschneidung ist riesig. Wir würden uns freuen dich im Team begrüßen zu dürfen und unsere Kräfte zu bündeln.

**Comment by dwt** [comment]
Ja aber gerne - wie kriegen wir es den hin uns im laufe des Tages mal zusammen zu telefonieren? Audio geht mit Sicherheit schneller als Text um zügig zu koordinieren.

**Comment by dwt** [comment]
Mein Vorschlag wäre dass wir uns heute Nachmittag Abend mal via http://meet.jit.si/private_tracing unterhalten?

**Comment by kreativmonkey** [comment]
Sorry, das ist in der Masse an Mails und Nachrichten einfach untergegangen gestern. Aber es hat ja nun geklappt ;-).
